theme = "catppuccin_mocha"

[editor]
true-color = true
line-number = "relative"
mouse = false
bufferline = "multiple"
cursorline = true
rulers = [120]

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
auto-signature-help = true
display-signature-help-docs = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"

[keys.normal]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
esc = ["collapse_selection", "keep_primary_selection"]
