theme = "tokyonight"

[editor]
true-color = true
line-number = "relative"
mouse = false
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
display-messages = true
auto-signature-help = true
display-signature-help-docs = true

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
# pageup = "no_op"
# pagedown = "no_op"
# home = "no_op"
# end = "no_op"

[keys.normal]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
# pageup = "no_op"
# pagedown = "no_op"
# home = "no_op"
# end = "no_op"
esc = ["collapse_selection", "keep_primary_selection"]
