# Rust configuration
[[language]]
name = "rust"
auto-format = true
indent = { tab-width = 4, unit = " " }

[language.language-server]
command = "rustup"
args = ["run", "stable", "rust-analyzer"]

[language.config.check]
command = "clippy"

# Golang configuration
[[language]]
name = "go"
scope = "source.go"
injection-regex = "go"
file-types = ["go"]
roots = ["Gopkg.toml", "go.mod"]
auto-format = true
formatter = { command = "goimports" }
language-server = { command = "gopls"}
comment-token = "//"
# golang needs utf-8 offsets
indent = { tab-width = 4, unit = "\t"}

[language.config.hints]
assignVariableTypes = true
compositeLiteralFields = true
constantValues = true
functionTypeParameters = true
parameterTypes = true
rangeVariableTypes = true

# C# configuration
[[language]]
name = "c-sharp"
scope = "source.cs"
injection-regex = "c-?sharp"
roots = ["sln", "csproj"]
file-types = ["cs"]
comment-token = "//"
indent = { tab-width = 4, unit = " " }
language-server = { command = "omnisharp", args = ["-lsp"], timeout=10000 }