# Rust configuration
[[language]]
name = "rust"
auto-format = true
indent = { tab-width = 4, unit = " " }
language-servers = ["rust-analyzer"]

[language-server.rust-analyzer.config]
checkOnSave = { command = "clippy" }

# Golang configuration
[[language]]
name = "go"
scope = "source.go"
injection-regex = "go"
file-types = ["go"]
roots = ["Gopkg.toml", "go.mod"]
auto-format = true
formatter = { command = "goimports" }
language-servers = ["gopls"]
comment-token = "//"
# golang needs utf-8 offsets
indent = { tab-width = 4, unit = "\t"}

[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
language-servers = ["typescript-language-server"]

[[language]]
name = "javascript"
language-servers = ["typescript-language-server"]

[[language]] 
name = "jsx"
language-servers = ["typescript-language-server"]


[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }

