map ge scrollToBottom
map <c-u> scrollPageUp
map <c-d> scrollPageDown
map <c-f> scrollFullPageDown
map <c-b> scrollFullPageUp
map zh scrollToLeft
map zl scrollToRight
map gh firstTab
map gp previousTab
map gn nextTab
map ga visitPreviousTab
map gl lastTab
map d removeTab
map u restoreTab
map e Vomnibar.activateEditUrl
map E Vomnibar.activateEditUrlInNewTab
map x enterVisualLineMode
map X enterVisualLineMode
map \ passNextKey